<BottomNav>
    adaptive_height:True
    spacing:"10dp"
    padding:"10dp"

    MDIconButton:
        icon:"home"

    MDIconButton:
        icon:"magnify"

    MDIconButton:
        icon:"movie"

    MDIconButton:
        icon:"heart-outline"

    FitImage:
        source:"image_2.jpeg"
        size_hint:None,None
        size:["25dp","25dp"]
        radius:[25,]
        pos_hint:{"center_x":.5,"center_y":.5}